/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.BenhNhanBUS;
import BUS.NhaSiBUS;
import DTO.BenhNhanDTO;
import Utils.BenhNhanUtils;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huyng
 */
public class BenhNhanGUI extends javax.swing.JPanel {

    /**
     * Creates new form NhaSiGUI
     */
    public BenhNhanGUI() {
        initComponents();
        loadDataToTable();
    }

    private void loadDataToTable() {
        DefaultTableModel model = (DefaultTableModel) tableBenhNhan.getModel();
        model.setRowCount(0); // Clear existing data from the table
        model.setColumnCount(0);
        model.addColumn("Mã bệnh nhân");
        model.addColumn("Tên bệnh nhân");
        model.addColumn("Tuổi");
        model.addColumn("Giới tính");
        model.addColumn("Sức khỏe răng miệng");
        List<BenhNhanDTO> danhSachBenhNhan = BenhNhanBUS.layDanhSachBenhNhan();

        for (BenhNhanDTO benhNhan : danhSachBenhNhan) {
            Object[] rowData = {benhNhan.getMaBenhNhan(), benhNhan.getTenBenhNhan(), benhNhan.getTuoi(), benhNhan.getGioiTinh(), benhNhan.getSucKhoeRangMieng()};
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableBenhNhan = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMaBenhNhan = new javax.swing.JTextField();
        txtTenBenhNhan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTuoi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboGioiTinh = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSucKhoeRangMieng = new javax.swing.JTextArea();
        btnChiTiet = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1366, 760));

        tableBenhNhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBenhNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBenhNhanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBenhNhan);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã bệnh nhân:");

        jLabel2.setText("Tên bệnh nhân:");

        txtTuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTuoiActionPerformed(evt);
            }
        });

        jLabel3.setText("Tuổi:");

        jLabel4.setText("Giới tính:");

        jLabel5.setText("Sức khỏe răng miệng:");

        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));

        txtSucKhoeRangMieng.setColumns(20);
        txtSucKhoeRangMieng.setRows(5);
        jScrollPane2.setViewportView(txtSucKhoeRangMieng);

        btnChiTiet.setText("Chi tiết");
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMaBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(98, 98, 98)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTenBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSua)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnChiTiet))
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThem)
                            .addComponent(txtMaBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua)
                            .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChiTiet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String maBenhNhan = txtMaBenhNhan.getText();
        String tenBenhNhan = txtTenBenhNhan.getText();
        int tuoi = Integer.parseInt(txtTuoi.getText());
        String gioiTinh = (String) cboGioiTinh.getSelectedItem();
        String sucKhoeRangMieng = txtSucKhoeRangMieng.getText();
        BenhNhanDTO benhNhanDTO = new BenhNhanDTO(maBenhNhan, tenBenhNhan, tuoi, gioiTinh, sucKhoeRangMieng);
        // Gọi phương thức NhaSiBUS.themNhaSi(nhaSiDTO) để thêm nhà sĩ vào cơ sở dữ liệu
        if (BenhNhanBUS.themBenhNhan(benhNhanDTO)) {
            JOptionPane.showMessageDialog(this, "Thêm bệnh nhân thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            // Thêm thành công, cập nhật lại dữ liệu trong JTable hoặc làm gì đó khác (nếu cần)
            loadDataToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm bệnh nhân thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            // Thêm thất bại, hiển thị thông báo lỗi hoặc xử lý lỗi (nếu cần)
        }
        // Sau khi thêm thành công, cập nhật lại dữ liệu trong JTable hoặc thông báo thành công cho người dùng
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        // Kiểm tra xem có hàng nào được chọn không
        int selectedRow = tableBenhNhan.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn bệnh nhân cần xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Lấy dữ liệu từ hàng nhà sĩ được chọn
        DefaultTableModel model = (DefaultTableModel) tableBenhNhan.getModel();
        String maBenhNhan = model.getValueAt(selectedRow, 0).toString(); // Giả sử cột MaNhaSi ở cột đầu tiên

        // Hiển thị hộp thoại xác nhận xóa nhà sĩ
        int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa bệnh nhân này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            // Nếu người dùng chọn Yes, thực hiện xóa nhà sĩ từ CSDL
            boolean isXoaBenhNhanSuccess = BenhNhanBUS.xoaBenhNhan(maBenhNhan);

            if (isXoaBenhNhanSuccess) {
                // Nếu xóa thành công, cập nhật lại dữ liệu trong JTable
                model.removeRow(selectedRow);
                JOptionPane.showMessageDialog(this, "Xóa bệnh nhân thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadDataToTable();
            } else {
                // Nếu xóa thất bại, hiển thị thông báo lỗi
                JOptionPane.showMessageDialog(this, "Xóa bệnh nhân thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnXoaActionPerformed
    }
    private ChiTietBenhNhanGUI panelChiTietBenhNhan;
    private void tableBenhNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBenhNhanMouseClicked
        // TODO add your handling code here:
        // Lấy chỉ số hàng được chọn
        int selectedRow = tableBenhNhan.getSelectedRow();

        // Kiểm tra nếu có hàng được chọn
        if (selectedRow >= 0) {
            // Lấy giá trị từ các cột của hàng được chọn
            String maNhaSi = tableBenhNhan.getValueAt(selectedRow, 0).toString();
            String tenNhaSi = tableBenhNhan.getValueAt(selectedRow, 1).toString();
            int tuoi = Integer.parseInt(tableBenhNhan.getValueAt(selectedRow, 2).toString());
            String gioiTinh = tableBenhNhan.getValueAt(selectedRow, 3).toString();
            String sucKhoeRangMieng = tableBenhNhan.getValueAt(selectedRow, 4).toString();

            // Điền dữ liệu vào các trường tương ứng
            txtMaBenhNhan.setText(maNhaSi);
            txtTenBenhNhan.setText(tenNhaSi);
            txtTuoi.setText(String.valueOf(tuoi));
            cboGioiTinh.setSelectedItem(gioiTinh);
            txtSucKhoeRangMieng.setText(sucKhoeRangMieng);
        }
    }//GEN-LAST:event_tableBenhNhanMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        // Kiểm tra xem có nha sĩ nào được chọn trong bảng hay không
        int selectedRow = tableBenhNhan.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một nha sĩ để sửa.");
            return;
        }

        // Lấy thông tin nha sĩ được chọn từ bảng
        String maBenhNhan = tableBenhNhan.getValueAt(selectedRow, 0).toString();
        String tenBenhNhan = txtTenBenhNhan.getText();
        int tuoi = Integer.parseInt(txtTuoi.getText());
        String gioiTinh = (String) cboGioiTinh.getSelectedItem();
        String sucKhoeRangMieng = txtSucKhoeRangMieng.getText();
        BenhNhanDTO benhNhanDTO = new BenhNhanDTO(maBenhNhan, tenBenhNhan, tuoi, gioiTinh, sucKhoeRangMieng);
        // Gọi phương thức NhaSiBUS.themNhaSi(nhaSiDTO) để thêm nhà sĩ vào cơ sở dữ liệu
        if (BenhNhanBUS.suaBenhNhan(benhNhanDTO)) {
            JOptionPane.showMessageDialog(this, "Sửa bệnh nhân thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            // Thêm thành công, cập nhật lại dữ liệu trong JTable hoặc làm gì đó khác (nếu cần)
            loadDataToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa bệnh nhân thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            // Thêm thất bại, hiển thị thông báo lỗi hoặc xử lý lỗi (nếu cần)
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtTuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTuoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTuoiActionPerformed
    
    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
        // TODO add your handling code here:
         int selectedRow = tableBenhNhan.getSelectedRow();

        // Kiểm tra nếu có hàng được chọn
        if (selectedRow >= 0) {
            // Lấy giá trị từ các cột của hàng được chọn
            String maBenhNhan = tableBenhNhan.getValueAt(selectedRow, 0).toString();
            BenhNhanUtils.chiTietBenhNhanDTO = BenhNhanBUS.layThongTinChiTietBenhNhan(maBenhNhan);
            BenhNhanUtils.chiTietBenhNhanDTO.setMaBenhNhan(maBenhNhan);
            BenhNhanUtils.chongChiDinhDTO = BenhNhanBUS.layChongChiDinhTheoMaBenhNhan(maBenhNhan);
            BenhNhanUtils.keHoachDieuTriDTO = BenhNhanBUS.layKeHoachDieuTriTheoMaBenhNhan(maBenhNhan);
            // TODO add your handling code here:
              panelChiTietBenhNhan = new ChiTietBenhNhanGUI();
        this.panelChiTietBenhNhan.setVisible(true);
        this.setLayout(new FlowLayout());
        this.removeAll();
        this.add(panelChiTietBenhNhan, BorderLayout.CENTER);
        this.updateUI();

        // Cập nhật lại giao diện
        this.revalidate();
        this.repaint();
            
        }
    }//GEN-LAST:event_btnChiTietActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboGioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableBenhNhan;
    private javax.swing.JTextField txtMaBenhNhan;
    private javax.swing.JTextArea txtSucKhoeRangMieng;
    private javax.swing.JTextField txtTenBenhNhan;
    private javax.swing.JTextField txtTuoi;
    // End of variables declaration//GEN-END:variables
}
