/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.BenhNhanBUS;
import BUS.ChongChiDinhBUS;
import BUS.NhaSiBUS;
import BUS.ThuocBUS;
import DTO.BenhNhanDTO;
import DTO.ChongChiDinhDTO;
import DTO.KeHoachDieuTriDTO;
import DTO.NhaSiDTO;
import DTO.ThuocDTO;
import Utils.BenhNhanUtils;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huyng
 */
public class ChiTietBenhNhanGUI extends javax.swing.JPanel {

    /**
     * Creates new form NhaSiGUI
     */
    public ChiTietBenhNhanGUI() {
        initComponents();
        loadDataToTable();
        loadChiTietBenhNhan();
        loadChongChiDinh();
        loadKeHoachDieuTri();
        loadThuoc();
    }
    private void loadChiTietBenhNhan(){
    txtTenBenhNhan.setText(BenhNhanUtils.chiTietBenhNhanDTO.getTenBenhNhan());
    txtTuoi.setText(BenhNhanUtils.chiTietBenhNhanDTO.getTuoi() + "");
    txtGioiTinh.setText(BenhNhanUtils.chiTietBenhNhanDTO.getGioiTinh());
    txtTongTienDieuTri.setText(BenhNhanUtils.chiTietBenhNhanDTO.getTongTienDieuTri() + "");
    txtTienDaThanhToan.setText(BenhNhanUtils.chiTietBenhNhanDTO.getTongTienDaThanhToan() + "");
    txtSucKhoeRangMieng.setText(BenhNhanUtils.chiTietBenhNhanDTO.getSucKhoeRangMieng());
    }
    private void loadChongChiDinh(){
            DefaultTableModel model = (DefaultTableModel) tableChongChiDinh.getModel();
        model.setRowCount(0); // Clear existing data from the table
        model.setColumnCount(0);
        model.addColumn("Mã chống chỉ định");
        model.addColumn("Mã thuốc");
        model.addColumn("Tên thuốc");
        model.addColumn("Ghi chú");
        BenhNhanUtils.chongChiDinhDTO = BenhNhanBUS.layChongChiDinhTheoMaBenhNhan(BenhNhanUtils.chiTietBenhNhanDTO.getMaBenhNhan());
        List<ChongChiDinhDTO> danhSachChongChiDinh = BenhNhanUtils.chongChiDinhDTO;

        for (ChongChiDinhDTO chongChiDinh : danhSachChongChiDinh) {
            Object[] rowData = {chongChiDinh.getMaChongChiDinh(), chongChiDinh.getMaThuoc(),chongChiDinh.getTenThuoc(), chongChiDinh.getGhiChu()};
            model.addRow(rowData);
        }
    }
       private void loadKeHoachDieuTri(){
            DefaultTableModel model = (DefaultTableModel) tableKeHoachDieuTri.getModel();
        model.setRowCount(0); // Clear existing data from the table
        model.setColumnCount(0);
        model.addColumn("Mã kế hoạch");
        model.addColumn("Mã nha sĩ");
        model.addColumn("Tên nha sĩ");
        model.addColumn("Ngày điều trị");
        model.addColumn("Mô tả");
        model.addColumn("Ghi chú");
        model.addColumn("Trạng thái điều trị");
            tableKeHoachDieuTri.getColumnModel().getColumn(0).setCellRenderer(new CustomTableCellRenderer());
    tableKeHoachDieuTri.getColumnModel().getColumn(1).setCellRenderer(new CustomTableCellRenderer());
    tableKeHoachDieuTri.getColumnModel().getColumn(2).setCellRenderer(new CustomTableCellRenderer());
    tableKeHoachDieuTri.getColumnModel().getColumn(3).setCellRenderer(new CustomTableCellRenderer());
    tableKeHoachDieuTri.getColumnModel().getColumn(4).setCellRenderer(new CustomTableCellRenderer());
    tableKeHoachDieuTri.getColumnModel().getColumn(5).setCellRenderer(new CustomTableCellRenderer());
    tableKeHoachDieuTri.getColumnModel().getColumn(6).setCellRenderer(new CustomTableCellRenderer());
        List<KeHoachDieuTriDTO> keHoachDieuTriDTO = BenhNhanUtils.keHoachDieuTriDTO;

        for (KeHoachDieuTriDTO keHoachDieuTri : keHoachDieuTriDTO) {
            Object[] rowData = {keHoachDieuTri.getMaKeHoach(), keHoachDieuTri.getMaNhaSi(),keHoachDieuTri.getTenNhaSi(), keHoachDieuTri.getNgayDieuTri(),keHoachDieuTri.getMoTa(),keHoachDieuTri.getGhiChu(), keHoachDieuTri.getTrangThaiDieuTri()};
            model.addRow(rowData);
        }
    }
       
    private void loadDataToTable() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTenBenhNhan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTuoi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSucKhoeRangMieng = new javax.swing.JTextArea();
        txtGioiTinh = new javax.swing.JTextField();
        txtTongTienDieuTri = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTienDaThanhToan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableChongChiDinh = new javax.swing.JTable();
        btnThemCCD = new javax.swing.JButton();
        btnSuaCCD = new javax.swing.JButton();
        btnXoaCCD = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableKeHoachDieuTri = new javax.swing.JTable();
        btnThemKeHoach = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboThuoc = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1366, 760));

        jLabel2.setText("Tên bệnh nhân:");

        txtTuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTuoiActionPerformed(evt);
            }
        });

        jLabel3.setText("Tuổi:");

        jLabel4.setText("Giới tính:");

        jLabel5.setText("Sức khỏe răng miệng:");

        txtSucKhoeRangMieng.setColumns(20);
        txtSucKhoeRangMieng.setRows(5);
        jScrollPane2.setViewportView(txtSucKhoeRangMieng);

        txtGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGioiTinhActionPerformed(evt);
            }
        });

        txtTongTienDieuTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienDieuTriActionPerformed(evt);
            }
        });

        jLabel6.setText("Tổng tiền điều trị:");

        txtTienDaThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienDaThanhToanActionPerformed(evt);
            }
        });

        jLabel7.setText("Tiền đã thanh toán:");

        tableChongChiDinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableChongChiDinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableChongChiDinhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableChongChiDinh);

        btnThemCCD.setText("Thêm");
        btnThemCCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCCDActionPerformed(evt);
            }
        });

        btnSuaCCD.setText("Sửa");
        btnSuaCCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaCCDActionPerformed(evt);
            }
        });

        btnXoaCCD.setText("Xóa");
        btnXoaCCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCCDActionPerformed(evt);
            }
        });

        tableKeHoachDieuTri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tableKeHoachDieuTri);

        btnThemKeHoach.setText("Thêm kế hoạch");
        btnThemKeHoach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKeHoachActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("THÔNG TIN CHI TIẾT BỆNH NHÂN");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("CHỐNG CHỈ ĐỊNH");

        cboThuoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Thuốc");

        jLabel10.setText("Ghi chú:");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane5.setViewportView(txtGhiChu);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("KẾ HOẠCH ĐIỀU TRỊ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTongTienDieuTri)
                                            .addComponent(txtTienDaThanhToan)))
                                    .addComponent(jScrollPane2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtGioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                                .addComponent(txtTuoi)
                                                .addComponent(txtTenBenhNhan))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(cboThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThemCCD, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnXoaCCD, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSuaCCD, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemKeHoach))
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(205, 205, 205))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtTenBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtTongTienDieuTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtTienDaThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(381, 381, 381)
                                .addComponent(btnThemCCD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(btnSuaCCD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnXoaCCD)
                                .addGap(33, 33, 33)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThemKeHoach)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtTuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTuoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTuoiActionPerformed
private void loadThuoc() {
    DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
    cboThuoc.setModel(comboBoxModel); // Set the model for the JComboBox

    // Load danh sách thuốc into the JComboBox
    List<ThuocDTO> danhSachThuoc = ThuocBUS.layDanhSachThuoc();
    for (ThuocDTO thuoc : danhSachThuoc) {
        comboBoxModel.addElement(thuoc.getMaThuoc() + "-" + thuoc.getTenThuoc()); // Add each drug's name to the JComboBox
    }
}

    private void txtGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGioiTinhActionPerformed

    private void txtTongTienDieuTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienDieuTriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienDieuTriActionPerformed

    private void txtTienDaThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienDaThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienDaThanhToanActionPerformed
private KeHoachDieuTriGUI panelKeHoachDieuTri;
    private void btnThemKeHoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKeHoachActionPerformed
        // TODO add your handling code here:
        panelKeHoachDieuTri = new KeHoachDieuTriGUI();
        this.panelKeHoachDieuTri.setVisible(true);
        this.setLayout(new FlowLayout());
        this.removeAll();
        this.add(panelKeHoachDieuTri, BorderLayout.CENTER);
        this.updateUI();

        // Cập nhật lại giao diện
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnThemKeHoachActionPerformed

    private void btnThemCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCCDActionPerformed
        // TODO add your handling code here:
     String maBenhNhan = BenhNhanUtils.chiTietBenhNhanDTO.getMaBenhNhan();
     String maThuoc = cboThuoc.getSelectedItem().toString().split("-")[0];
     String ghiChu = txtGhiChu.getText();
     ChongChiDinhDTO chongChiDinhDTO = new ChongChiDinhDTO(maBenhNhan,maThuoc, ghiChu);
        
        // Gọi phương thức NhaSiBUS.themNhaSi(nhaSiDTO) để thêm nhà sĩ vào cơ sở dữ liệu
        if (ChongChiDinhBUS.themChongChiDinh(chongChiDinhDTO)) {
            JOptionPane.showMessageDialog(this, "Thêm chống chỉ định thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            // Thêm thành công, cập nhật lại dữ liệu trong JTable hoặc làm gì đó khác (nếu cần)
            loadDataToTable();
                loadChongChiDinh();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm chống chỉ định thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            // Thêm thất bại, hiển thị thông báo lỗi hoặc xử lý lỗi (nếu cần)
        }
    }//GEN-LAST:event_btnThemCCDActionPerformed

    private void btnXoaCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCCDActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        // Kiểm tra xem có hàng nào được chọn không
        int selectedRow = tableChongChiDinh.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn chống chỉ định cần xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Lấy dữ liệu từ hàng nhà sĩ được chọn
        DefaultTableModel model = (DefaultTableModel) tableChongChiDinh.getModel();
        String maChongChiDinh = model.getValueAt(selectedRow, 0).toString(); // Giả sử cột MaNhaSi ở cột đầu tiên

        // Hiển thị hộp thoại xác nhận xóa nhà sĩ
        int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa chống chỉ định này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            // Nếu người dùng chọn Yes, thực hiện xóa nhà sĩ từ CSDL
            boolean isXoaNhaSiSuccess = ChongChiDinhBUS.xoaChongChiDinh(maChongChiDinh);

            if (isXoaNhaSiSuccess) {
                // Nếu xóa thành công, cập nhật lại dữ liệu trong JTable
                model.removeRow(selectedRow);
                JOptionPane.showMessageDialog(this, "Xóa chống chỉ định thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadDataToTable();
                loadChongChiDinh();
            } else {
                // Nếu xóa thất bại, hiển thị thông báo lỗi
                JOptionPane.showMessageDialog(this, "Xóa chống chỉ định thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
    }           
    }//GEN-LAST:event_btnXoaCCDActionPerformed

    private void tableChongChiDinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableChongChiDinhMouseClicked
        // TODO add your handling code here:
        int selectedRow = tableChongChiDinh.getSelectedRow();

        // Kiểm tra nếu có hàng được chọn
        if (selectedRow >= 0) {
            // Lấy giá trị từ các cột của hàng được chọn
            String maChongChiDinh = tableChongChiDinh.getValueAt(selectedRow, 0).toString();
            String maThuoc = tableChongChiDinh.getValueAt(selectedRow, 1).toString();
            String tenThuoc = tableChongChiDinh.getValueAt(selectedRow, 2).toString();
            String ghiChu = tableChongChiDinh.getValueAt(selectedRow, 3).toString();

            cboThuoc.setSelectedItem( maThuoc + "-" + tenThuoc);
            txtGhiChu.setText(ghiChu);
        }
    }//GEN-LAST:event_tableChongChiDinhMouseClicked

    private void btnSuaCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaCCDActionPerformed
       int selectedRow = tableChongChiDinh.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một chống chỉ định để sửa.");
            return;
        }

        // Lấy thông tin nha sĩ được chọn từ bảng
        int maChongChiDinh = Integer.parseInt(tableChongChiDinh.getValueAt(selectedRow, 0).toString());
     String maBenhNhan = BenhNhanUtils.chiTietBenhNhanDTO.getMaBenhNhan();
     String maThuoc = cboThuoc.getSelectedItem().toString().split("-")[0];
     String ghiChu = txtGhiChu.getText();
     ChongChiDinhDTO chongChiDinhDTO = new ChongChiDinhDTO(maChongChiDinh, maBenhNhan,maThuoc, ghiChu);
        
        // Gọi phương thức NhaSiBUS.themNhaSi(nhaSiDTO) để thêm nhà sĩ vào cơ sở dữ liệu
        if (ChongChiDinhBUS.suaChongChiDinh(chongChiDinhDTO)) {
            JOptionPane.showMessageDialog(this, "Sửa chống chỉ định thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            // Thêm thành công, cập nhật lại dữ liệu trong JTable hoặc làm gì đó khác (nếu cần)
            loadDataToTable();
                loadChongChiDinh();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa chống chỉ định thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            // Thêm thất bại, hiển thị thông báo lỗi hoặc xử lý lỗi (nếu cần)
        }
    }//GEN-LAST:event_btnSuaCCDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaCCD;
    private javax.swing.JButton btnThemCCD;
    private javax.swing.JButton btnThemKeHoach;
    private javax.swing.JButton btnXoaCCD;
    private javax.swing.JComboBox<String> cboThuoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tableChongChiDinh;
    private javax.swing.JTable tableKeHoachDieuTri;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtGioiTinh;
    private javax.swing.JTextArea txtSucKhoeRangMieng;
    private javax.swing.JTextField txtTenBenhNhan;
    private javax.swing.JTextField txtTienDaThanhToan;
    private javax.swing.JTextField txtTongTienDieuTri;
    private javax.swing.JTextField txtTuoi;
    // End of variables declaration//GEN-END:variables
}
