/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.BenhNhanBUS;
import BUS.LichHenBUS;
import BUS.NhaSiBUS;
import BUS.NhanVienBUS;
import BUS.ThuocBUS;
import DTO.BenhNhanDTO;
import DTO.LichHenDTO;
import DTO.NhaSiDTO;

import DTO.NhanVienDTO;
import DTO.ThuocDTO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class LichHenGUI extends javax.swing.JPanel {

    /**
     * Creates new form NhanVienGUI
     */
    public LichHenGUI() {
        initComponents();
        loadDataToTable();
        loadBenhNhan() ;
        loadNhaSi();
    }
private void loadBenhNhan() {
    DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
    cboBenhNhan.setModel(comboBoxModel); // Set the model for the JComboBox

    // Load danh sách thuốc into the JComboBox
    List<BenhNhanDTO> benhNhanDTO = BenhNhanBUS.layDanhSachBenhNhan();
    for (BenhNhanDTO benhNhan : benhNhanDTO) {
        comboBoxModel.addElement(benhNhan.getMaBenhNhan()); // Add each drug's name to the JComboBox
    }
}
private void loadNhaSi() {
    DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
    cboNhaSi.setModel(comboBoxModel); // Set the model for the JComboBox

    // Load danh sách thuốc into the JComboBox
    List<NhaSiDTO> nhaSiDTO = NhaSiBUS.layDanhSachNhaSi();
    for (NhaSiDTO nhasi : nhaSiDTO) {
        comboBoxModel.addElement(nhasi.getMaNhaSi()); // Add each drug's name to the JComboBox
    }
}
    private void loadDataToTable() {
        DefaultTableModel model = (DefaultTableModel) tableLichHen.getModel();
        model.setRowCount(0); // Clear existing data from the table
        model.setColumnCount(0);
        model.addColumn("Mã lịch hẹn");
        model.addColumn("Thời gian hẹn");
        model.addColumn("Mã bệnh nhân");
        model.addColumn("Ma nha sĩ");
        model.addColumn("Phòng khám");
        model.addColumn("Tình trạng");
        List<LichHenDTO> lichHenDTO = LichHenBUS.layDanhSachLichHen();

        for (LichHenDTO nhaSi : lichHenDTO) {
            Object[] rowData = {nhaSi.getMaLichHen(), nhaSi.getThoiGianHen(), nhaSi.getMaBenhNhan(), nhaSi.getMaNhaSi(), nhaSi.getPhongKham(), nhaSi.getTinhTrang()};
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableLichHen = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMaLichHen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPhongKham = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboNhaSi = new javax.swing.JComboBox<>();
        dateChooserThoiGianHen = new com.toedter.calendar.JDateChooser();
        cboBenhNhan = new javax.swing.JComboBox<>();
        txtTinhTrang = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1366, 760));

        tableLichHen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã lịch hẹn", "Thời gian hẹn", "Mã bệnh nhân", "Mã nha sĩ", "Phòng khám", "Tình trạng"
            }
        ));
        tableLichHen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLichHenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableLichHen);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã lịch hẹn:");

        jLabel2.setText("Thời gian hẹn:");

        jLabel3.setText("Bệnh nhân:");

        jLabel4.setText("Nha sĩ:");

        jLabel5.setText("Phòng khám:");

        jLabel6.setText("Tình trạng:");

        cboNhaSi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));

        cboBenhNhan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPhongKham, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaLichHen, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboNhaSi, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateChooserThoiGianHen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem)
                    .addComponent(btnXoa))
                .addGap(151, 151, 151))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaLichHen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cboBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPhongKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(btnThem))
                            .addComponent(dateChooserThoiGianHen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cboNhaSi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(btnXoa)
                            .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String maNhanVien = txtMaLichHen.getText();
        String thoiGianHen = dateChooserThoiGianHen.getDate().toString();

        SimpleDateFormat dateFormat = new SimpleDateFormat("EEE MMM dd HH:mm:ss zzz yyyy");
        Date date;
        try {
            date = dateFormat.parse(thoiGianHen);
        } catch (ParseException e) {
            e.printStackTrace();
            return; // Xử lý lỗi nếu có thể
        }

// Chuyển đổi thành java.sql.Date
        java.sql.Date sqlDate = new java.sql.Date(date.getTime());
        System.out.println(sqlDate);
        String maBenhNhan = (String) cboBenhNhan.getSelectedItem();
        String maNhaSi = (String) cboNhaSi.getSelectedItem();
        String phongKham = txtPhongKham.getText();
        String tinhTrang = txtTinhTrang.getText();
        LichHenDTO lichHenDTO = new LichHenDTO(sqlDate, maBenhNhan, maNhaSi, phongKham, tinhTrang);
        // Gọi phương thức NhanVienBUS.themNhanVien(nhaSiDTO) để thêm nhà sĩ vào cơ sở dữ liệu
        if (LichHenBUS.themLichHen(lichHenDTO)) {
            JOptionPane.showMessageDialog(this, "Thêm lịch hẹn thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            // Thêm thành công, cập nhật lại dữ liệu trong JTable hoặc làm gì đó khác (nếu cần)
            loadDataToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm lịch hẹn thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            // Thêm thất bại, hiển thị thông báo lỗi hoặc xử lý lỗi (nếu cần)
        }
        // Sau khi thêm thành công, cập nhật lại dữ liệu trong JTable hoặc thông báo thành công cho người dùng
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        // Kiểm tra xem có hàng nào được chọn không
        int selectedRow = tableLichHen.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn lịch hẹn cần xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Lấy dữ liệu từ hàng nhà sĩ được chọn
        DefaultTableModel model = (DefaultTableModel) tableLichHen.getModel();
        String maNhanVien = model.getValueAt(selectedRow, 0).toString(); // Giả sử cột MaNhanVien ở cột đầu tiên

        // Hiển thị hộp thoại xác nhận xóa nhà sĩ
        int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa lịch hẹn này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            // Nếu người dùng chọn Yes, thực hiện xóa nhà sĩ từ CSDL
            boolean isXoaNhanVienSuccess = LichHenBUS.xoaLichHen(maNhanVien);

            if (isXoaNhanVienSuccess) {
                // Nếu xóa thành công, cập nhật lại dữ liệu trong JTable
                model.removeRow(selectedRow);
                JOptionPane.showMessageDialog(this, "Xóa lịch hẹn thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadDataToTable();
            } else {
                // Nếu xóa thất bại, hiển thị thông báo lỗi
                JOptionPane.showMessageDialog(this, "Xóa lịch hẹn thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnXoaActionPerformed
    }
    private void tableLichHenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLichHenMouseClicked
        // TODO add your handling code here:
        // Lấy chỉ số hàng được chọn
        int selectedRow = tableLichHen.getSelectedRow();

        // Kiểm tra nếu có hàng được chọn
        if (selectedRow >= 0) {
            // Lấy giá trị từ các cột của hàng được chọn
            String maLichHen = tableLichHen.getValueAt(selectedRow, 0).toString();
            String thoiGianHen = tableLichHen.getValueAt(selectedRow, 1).toString();
            String maBenhNhan = tableLichHen.getValueAt(selectedRow, 2).toString();
            String maNhaSi = tableLichHen.getValueAt(selectedRow, 3).toString();
            String phongKham = tableLichHen.getValueAt(selectedRow, 4).toString();
            String tinhTrang = tableLichHen.getValueAt(selectedRow, 5).toString();
            // Điền dữ liệu vào các trường tương ứng
            txtMaLichHen.setText(maLichHen);
            cboBenhNhan.setSelectedItem(maBenhNhan);
            cboNhaSi.setSelectedItem(maNhaSi);
            txtPhongKham.setText(phongKham);
            txtTinhTrang.setText(tinhTrang);
// Định dạng ngày từ chuỗi
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date date;
            try {
                date = dateFormat.parse(thoiGianHen);
            } catch (ParseException e) {
                e.printStackTrace();
                return; // Xử lý lỗi nếu có thể
            }

// Chuyển đổi thành java.sql.Date
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());

// Thiết lập ngày cho dateChooserThoiGianHen
            dateChooserThoiGianHen.setDate(date);

        }
    }//GEN-LAST:event_tableLichHenMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboBenhNhan;
    private javax.swing.JComboBox<String> cboNhaSi;
    private com.toedter.calendar.JDateChooser dateChooserThoiGianHen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLichHen;
    private javax.swing.JTextField txtMaLichHen;
    private javax.swing.JTextField txtPhongKham;
    private javax.swing.JTextField txtTinhTrang;
    // End of variables declaration//GEN-END:variables
}
