/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.NhaSiBUS;
import DTO.NhaSiDTO;
import Utils.DangNhapUtils;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huyng
 */
public class NhaSiGUI extends javax.swing.JPanel {

    /**
     * Creates new form NhaSiGUI
     */
    public NhaSiGUI() {
        initComponents();
        loadDataToTable();
        phanQuyen();
    }
   public void phanQuyen() {
        if (!"QuanTriVien".equals(DangNhapUtils.loaiTaiKhoan)) {
           btnThem.setEnabled(false);
           btnSua.setEnabled(false);
           btnXoa.setEnabled(false);
        }
    }
    private void loadDataToTable() {
        DefaultTableModel model = (DefaultTableModel) tableNhaSi.getModel();
        model.setRowCount(0); // Clear existing data from the table
        model.setColumnCount(0);
        model.addColumn("Mã nha sĩ");
        model.addColumn("Tên nha sĩ");
        model.addColumn("Tuổi");
        model.addColumn("Giới tính");
        model.addColumn("Địa chỉ");
        model.addColumn("Số điện thoại");
        model.addColumn("Mật khẩu");
        List<NhaSiDTO> danhSachNhaSi = NhaSiBUS.layDanhSachNhaSi();

        for (NhaSiDTO nhaSi : danhSachNhaSi) {
            Object[] rowData = {nhaSi.getMaNhaSi(), nhaSi.getTenNhaSi(), nhaSi.getTuoi(), nhaSi.getGioiTinh(), nhaSi.getDiaChi(), nhaSi.getSoDienThoai(), nhaSi.getPassword()};
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableNhaSi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaNhaSi = new javax.swing.JTextField();
        txtTuoi = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        cboGioiTinh = new javax.swing.JComboBox<>();
        txtTenNhaSi = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        tableNhaSi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableNhaSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNhaSiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableNhaSi);

        jLabel1.setText("Mã nha sĩ:");

        jLabel3.setText("Tuổi:");

        jLabel5.setText("Địa chỉ:");

        jLabel7.setText("Mật khẩu:");

        jLabel2.setText("Tên nha sĩ:");

        jLabel4.setText("Giới tính:");

        jLabel6.setText("Số điện thoại:");

        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtMaNhaSi, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenNhaSi, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(177, 177, 177)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSua)
                    .addComponent(btnThem)
                    .addComponent(btnXoa))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenNhaSi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtMaNhaSi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String maNhaSi = txtMaNhaSi.getText();
        String tenNhaSi = txtTenNhaSi.getText();
        int tuoi = Integer.parseInt(txtTuoi.getText());
        String gioiTinh = (String) cboGioiTinh.getSelectedItem();
        String diaChi = txtDiaChi.getText();
        String soDienThoai = txtSoDienThoai.getText();
        String matKhau = txtMatKhau.getText();
        NhaSiDTO nhaSiDTO = new NhaSiDTO(maNhaSi, tenNhaSi, tuoi, gioiTinh, diaChi, soDienThoai);
        nhaSiDTO.setPassword(matKhau);
        // Gọi phương thức NhaSiBUS.themNhaSi(nhaSiDTO) để thêm nhà sĩ vào cơ sở dữ liệu
        if (NhaSiBUS.themNhaSi(nhaSiDTO)) {
            JOptionPane.showMessageDialog(this, "Thêm nha sĩ thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            // Thêm thành công, cập nhật lại dữ liệu trong JTable hoặc làm gì đó khác (nếu cần)
            loadDataToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm nha sĩ thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            // Thêm thất bại, hiển thị thông báo lỗi hoặc xử lý lỗi (nếu cần)
        }
        // Sau khi thêm thành công, cập nhật lại dữ liệu trong JTable hoặc thông báo thành công cho người dùng
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        // Kiểm tra xem có hàng nào được chọn không
        int selectedRow = tableNhaSi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhà sĩ cần xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Lấy dữ liệu từ hàng nhà sĩ được chọn
        DefaultTableModel model = (DefaultTableModel) tableNhaSi.getModel();
        String maNhaSi = model.getValueAt(selectedRow, 0).toString(); // Giả sử cột MaNhaSi ở cột đầu tiên

        // Hiển thị hộp thoại xác nhận xóa nhà sĩ
        int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa nha sĩ này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            // Nếu người dùng chọn Yes, thực hiện xóa nhà sĩ từ CSDL
            boolean isXoaNhaSiSuccess = NhaSiBUS.xoaNhaSi(maNhaSi);

            if (isXoaNhaSiSuccess) {
                // Nếu xóa thành công, cập nhật lại dữ liệu trong JTable
                model.removeRow(selectedRow);
                JOptionPane.showMessageDialog(this, "Xóa nha sĩ thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadDataToTable();
            } else {
                // Nếu xóa thất bại, hiển thị thông báo lỗi
                JOptionPane.showMessageDialog(this, "Xóa nhà sĩ thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnXoaActionPerformed
    }
    private void tableNhaSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNhaSiMouseClicked
        // TODO add your handling code here:
        // Lấy chỉ số hàng được chọn
        int selectedRow = tableNhaSi.getSelectedRow();

        // Kiểm tra nếu có hàng được chọn
        if (selectedRow >= 0) {
            // Lấy giá trị từ các cột của hàng được chọn
            String maNhaSi = tableNhaSi.getValueAt(selectedRow, 0).toString();
            String tenNhaSi = tableNhaSi.getValueAt(selectedRow, 1).toString();
            int tuoi = Integer.parseInt(tableNhaSi.getValueAt(selectedRow, 2).toString());
            String gioiTinh = tableNhaSi.getValueAt(selectedRow, 3).toString();
            String diaChi = tableNhaSi.getValueAt(selectedRow, 4).toString();
            String soDienThoai = tableNhaSi.getValueAt(selectedRow, 5).toString();
String matKhau = tableNhaSi.getValueAt(selectedRow, 6).toString();
            // Điền dữ liệu vào các trường tương ứng
            txtMaNhaSi.setText(maNhaSi);
            txtTenNhaSi.setText(tenNhaSi);
            txtTuoi.setText(String.valueOf(tuoi));
            cboGioiTinh.setSelectedItem(gioiTinh);
            txtDiaChi.setText(diaChi);
            txtSoDienThoai.setText(soDienThoai);
            txtMatKhau.setText(matKhau);
        }
    }//GEN-LAST:event_tableNhaSiMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        // Kiểm tra xem có nha sĩ nào được chọn trong bảng hay không
        int selectedRow = tableNhaSi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một nha sĩ để sửa.");
            return;
        }

        // Lấy thông tin nha sĩ được chọn từ bảng
        String maNhaSi = tableNhaSi.getValueAt(selectedRow, 0).toString();
        String tenNhaSi = txtTenNhaSi.getText();
        int tuoi = Integer.parseInt(txtTuoi.getText());
        String gioiTinh = (String) cboGioiTinh.getSelectedItem();
        String diaChi = txtDiaChi.getText();
        String soDienThoai = txtSoDienThoai.getText();
        String matKhau = txtMatKhau.getText();
        NhaSiDTO nhaSiDTO = new NhaSiDTO(maNhaSi, tenNhaSi, tuoi, gioiTinh, diaChi, soDienThoai, matKhau);
        // Gọi phương thức NhaSiBUS.themNhaSi(nhaSiDTO) để thêm nhà sĩ vào cơ sở dữ liệu
        if (NhaSiBUS.suaNhaSi(nhaSiDTO)) {
            JOptionPane.showMessageDialog(this, "Sửa nha sĩ thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            // Thêm thành công, cập nhật lại dữ liệu trong JTable hoặc làm gì đó khác (nếu cần)
            loadDataToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa nha sĩ thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            // Thêm thất bại, hiển thị thông báo lỗi hoặc xử lý lỗi (nếu cần)
        }
    }//GEN-LAST:event_btnSuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboGioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableNhaSi;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaNhaSi;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenNhaSi;
    private javax.swing.JTextField txtTuoi;
    // End of variables declaration//GEN-END:variables
}
